### ISSUE TITLE
Laser_OS_Test.17.toe not working and crashing.

### ISSUE THREAD

**Issue by g-wizzy** [Wickedlasers/Laser_OS_TouchDesigner#7]
Hi,

I encountered a problem while trying out your plugin. After moving the content of the Plugins folder into `Documents/Derivative/Plugins`, as described in the README, I launched the sample `.toe` file. This is what appears when selecting the `Laseros1` node :

![image](https://user-images.githubusercontent.com/54360836/94682363-1e2ef800-0325-11eb-86c9-5737cbedd4b3.png)

Then, when enabling the laser output, the app crashes. Here is a crash dump:

[TouchDesignerCrash.2020.26630.1.zip](https://github.com/Wickedlasers/Laser_OS_TouchDesigner/files/5305238/TouchDesignerCrash.2020.26630.1.zip)

**Comment by tgreiser** [comment]
Are you able to select a different device? That actually looks like my device ID that must be cached in the control.

**Comment by tgreiser** [comment]
The DLLs are working because it is populating the device ID. I will need to follow up with Derivative to see about getting some info from the dump file.

**Comment by tgreiser** [comment]
Can you confirm what version of windows you are using @g-wizzy ?

**Comment by tgreiser** [comment]
If you want to follow along here: https://forum.derivative.ca/t/cplusplus-chop-crash-error/152124

**Comment by g-wizzy** [comment]
Thanks for the help. I'm not able to attempt anything until Monday, but I'll post if I find something that works.

**Comment by g-wizzy** [comment]
It was actually as simple as a missing driver ! Sorry for the trouble, and cheers.

**Comment by tgreiser** [comment]
@g-wizzy what driver was it?
